"""
Seeds the knowledge base with proven trading frameworks on first run.
Claude consults these before every signal + episode review.
"""
import uuid
from sqlalchemy.ext.asyncio import AsyncSession
from sqlalchemy import select, func
from app.db.models import KnowledgeEntry

SEED_KNOWLEDGE = [
    # ── Risk Management (20 entries) ──────────────────────────────────────────
    {
        "category": "risk_management",
        "market": "all",
        "title": "Kelly Criterion",
        "content": "Never risk more than the Kelly fraction of your bankroll on a single trade. Full Kelly is theoretically optimal but practically dangerous — use half-Kelly (0.25) to reduce variance while maintaining growth. Formula: f = (bp - q) / b where b=odds, p=win probability, q=loss probability.",
        "importance": 10,
        "tags": ["risk_management"],
    },
    {
        "category": "risk_management",
        "market": "all",
        "title": "Van Tharp Position Sizing",
        "content": "Risk 1-2% of total account equity per trade maximum. In high-volatility regimes (VIX>25), halve your normal position size. In extreme volatility (VIX>35), reduce to 25% of normal. The goal is survival first, profits second.",
        "importance": 10,
        "tags": ["risk_management", "vix_high", "crisis_volatility"],
    },
    {
        "category": "risk_management",
        "market": "all",
        "title": "Stop Loss Discipline",
        "content": "Always set a stop-loss BEFORE entering a position, never after. Never move a stop-loss against your position (down for longs, up for shorts). A stop-loss is a pre-committed exit — treating it as negotiable is the single largest cause of blow-ups.",
        "importance": 10,
        "tags": ["risk_management", "risk_off"],
    },
    {
        "category": "risk_management",
        "market": "all",
        "title": "Consecutive Losses Rule",
        "content": "After 3 consecutive losing trades, halve your position size for the next 5 trades. After 5 consecutive losses, stop trading for the session and review your thesis. Tilt (emotional over-trading after losses) is more dangerous than any single bad trade.",
        "importance": 9,
        "tags": ["risk_management", "crisis_volatility"],
    },
    {
        "category": "risk_management",
        "market": "all",
        "title": "Market Regime Filter",
        "content": "In Risk-Off regime: reduce leverage 50%, prefer HOLD or short side, tighten stops to 1.5% from entry. In Risk-On regime: normal sizing applies. In Neutral: use 75% of normal sizing. Regime is determined by VIX level + trend direction of major indices.",
        "importance": 9,
        "tags": ["risk_management", "vix_high", "risk_off", "macro_cycle"],
    },
    {
        "category": "risk_management",
        "market": "crypto",
        "title": "Liquidation Price Awareness",
        "content": "With 10x leverage, a 10% adverse move liquidates your position. Always set stops before liquidation. Rule: stop-loss must be at least 20% above liquidation price. Example: if liquidation at $50k BTC, stop at $60k minimum. Exchange liquidations cascade — once it starts, spreads widen to 2-5%.",
        "importance": 10,
        "tags": ["crypto", "risk_management", "vix_high"],
    },
    {
        "category": "risk_management",
        "market": "all",
        "title": "Correlation Risk in Portfolios",
        "content": "Crypto and US tech stocks have 0.7-0.85 correlation in risk-off regimes. Holding BTC + NVDA + AAPL is NOT diversification — it's 3x correlated tech exposure. In Risk-Off, all 3 fall simultaneously. True diversification requires assets with negative or zero correlation (gold, bonds, short positions).",
        "importance": 8,
        "tags": ["risk_management", "risk_off", "crypto", "us_stocks"],
    },
    {
        "category": "risk_management",
        "market": "all",
        "title": "Pre-Event Risk Reduction",
        "content": "Before high-impact events (FOMC, CPI, NFP), reduce position sizes to 50% of normal. Before extreme events (emergency Fed meetings, major geopolitical news), reduce to 25%. The market prices in the expected move, but the actual reaction is often opposite direction or 2-3x magnitude.",
        "importance": 9,
        "tags": ["risk_management", "fomc_week", "cpi_event", "nfp_event", "high_impact_event"],
    },
    {
        "category": "risk_management",
        "market": "all",
        "title": "Leverage Scaling Rules",
        "content": "VIX < 15: normal leverage (up to 10x for crypto, 5x for stocks). VIX 15-25: reduce to 60%. VIX 25-35: reduce to 40%. VIX > 35: maximum 2x leverage, prefer no leverage. High leverage in high volatility is a guaranteed path to liquidation via normal price noise.",
        "importance": 9,
        "tags": ["risk_management", "vix_high", "vix_extreme", "crisis_volatility"],
    },
    {
        "category": "risk_management",
        "market": "all",
        "title": "Take Profit Discipline",
        "content": "Set take-profit targets BEFORE entering. Minimum R:R ratio of 2:1 (take-profit distance must be 2x the stop-loss distance). Never remove take-profit targets in pursuit of more gain — partial profit-taking at 50% target and trailing stop for remainder is optimal.",
        "importance": 8,
        "tags": ["risk_management"],
    },
    {
        "category": "risk_management",
        "market": "all",
        "title": "News Embargo Rule",
        "content": "Do not enter new positions within 30 minutes before or after major economic releases (CPI, NFP, FOMC). Spreads widen, slippage increases 3-5x. The initial move is often reversed within 1 hour of the release. Wait for the second move after the market digests the news.",
        "importance": 8,
        "tags": ["risk_management", "fomc_week", "cpi_event", "nfp_event", "high_impact_event"],
    },
    {
        "category": "risk_management",
        "market": "all",
        "title": "Maximum Open Positions Rule",
        "content": "Never have more than 3 correlated open positions simultaneously. Across uncorrelated asset classes, maximum 6 positions. Each additional position reduces your ability to monitor and reduces per-position conviction. Quality over quantity.",
        "importance": 8,
        "tags": ["risk_management"],
    },
    {
        "category": "risk_management",
        "market": "us_stocks",
        "title": "US Market Hours Awareness",
        "content": "US stocks trade 9:30AM-4PM ET. First 30 minutes (9:30-10AM) are highest volatility — amateur hour with wide spreads. Last 30 minutes (3:30-4PM) sees institutional rebalancing — sharp directional moves. Best signal quality: 10AM-3PM ET. Avoid holding positions into close on FOMC/CPI days.",
        "importance": 8,
        "tags": ["us_stocks", "high_impact_event"],
    },
    {
        "category": "risk_management",
        "market": "india_stocks",
        "title": "India Market Session Rules",
        "content": "NSE/BSE trade 9:15AM-3:30PM IST. Pre-open 9:00-9:15AM sets opening price. F&O expiry every Thursday — extremely high volatility in last 2 hours. Monthly expiry (last Thursday) causes Nifty swings of 0.5-1.5%. Budget day (February) can move indices 3-5% either direction.",
        "importance": 8,
        "tags": ["india_stocks", "high_impact_event"],
    },
    {
        "category": "risk_management",
        "market": "all",
        "title": "Drawdown Recovery Math",
        "content": "A 10% loss requires 11% gain to recover. A 20% loss requires 25% gain. A 50% loss requires 100% gain. A 80% blow-up requires 400% gain. This asymmetry means capital preservation is paramount — it takes 4x the gain to recover from a large loss. Never let a single trade lose more than 5% of equity.",
        "importance": 9,
        "tags": ["risk_management", "crisis_volatility"],
    },
    {
        "category": "risk_management",
        "market": "crypto",
        "title": "Crypto Weekend Risk",
        "content": "Crypto markets operate 24/7 but liquidity is 40-60% lower on weekends. Weekend BTC moves of 5-10% are common with thin order books. Large liquidations cascade faster with lower liquidity. Reduce position sizes Friday evening, set wider stops or take partial profits before weekend if holding leveraged positions.",
        "importance": 7,
        "tags": ["crypto", "risk_management"],
    },
    {
        "category": "risk_management",
        "market": "all",
        "title": "Fear & Greed as Contrarian Signal",
        "content": "Extreme Fear (F&G < 20): historically 80% of the time leads to positive returns over next 30 days. Extreme Greed (F&G > 80): historically 70% chance of correction within 4 weeks. These are positioning signals, not immediate entry signals — sentiment can stay extreme for weeks. Use as a bias filter, not a trigger.",
        "importance": 7,
        "tags": ["extreme_fear", "extreme_greed", "crypto"],
    },
    {
        "category": "risk_management",
        "market": "forex",
        "title": "Forex Session Timing",
        "content": "Forex: London session (8AM-4PM GMT) is highest volume — best for EUR/GBP/CHF. New York session (1PM-9PM GMT) highest for USD pairs. Tokyo session (12AM-8AM GMT) best for JPY/AUD. Overlap periods (1-4PM GMT: London+NY) have maximum liquidity and tightest spreads. USD/INR most liquid 9AM-5PM IST.",
        "importance": 7,
        "tags": ["forex", "risk_management"],
    },
    {
        "category": "risk_management",
        "market": "all",
        "title": "Overnight Gap Risk",
        "content": "Stocks can gap up or down 2-20% at open due to earnings, news, or macro events. Overnight holds in leveraged positions during earnings season are gambling, not trading. If you must hold overnight: reduce leverage to 1-2x maximum, set stops 5-8% below entry to survive reasonable gaps.",
        "importance": 8,
        "tags": ["risk_management", "us_stocks", "india_stocks", "high_impact_event"],
    },
    {
        "category": "risk_management",
        "market": "all",
        "title": "Win Rate vs R:R Tradeoff",
        "content": "A 40% win rate with 3:1 R:R is more profitable than 70% win rate with 1:1. With 3:1 R:R: 40 wins x 3 - 60 losses x 1 = +60 units. With 1:1: 70 wins - 30 losses = +40 units. High win rate feels good but destroys edge when losers are too large. Focus on R:R first, win rate second.",
        "importance": 8,
        "tags": ["risk_management"],
    },

    # ── Crash History (18 entries) ────────────────────────────────────────────
    {
        "category": "crash_history",
        "market": "all",
        "title": "2008 Global Financial Crisis Playbook",
        "content": "Lehman collapse (Sept 2008) triggered 18-month bear market: S&P500 -57%, banks -80%, credit frozen. Gold initially fell (liquidity crisis), then rose 150% in recovery. BUY: gold, treasuries, utilities. AVOID: financials, real estate, consumer discretionary. VIX peaked at 89. Bear market lasted 17 months.",
        "importance": 9,
        "tags": ["crash_history", "risk_off", "vix_extreme", "crisis_volatility", "contagion_risk", "recession_risk", "gold_spike"],
    },
    {
        "category": "crash_history",
        "market": "all",
        "title": "COVID-19 Crash 2020 — V-Shaped Recovery",
        "content": "Feb-March 2020: S&P500 -34% in 33 days (fastest ever). Recovery was equally fast — full recovery in 5 months. Pattern: massive Fed QE + fiscal stimulus = V-shape. Crypto fell 50% in 2 days (March 12-13), then rallied 600% over next year. Lesson: central bank response determines recovery speed. Watch for Fed emergency actions.",
        "importance": 9,
        "tags": ["crash_history", "risk_off", "vix_extreme", "crisis_volatility", "crypto"],
    },
    {
        "category": "crash_history",
        "market": "us_stocks",
        "title": "Dot-Com Bubble 2000-2002",
        "content": "Nasdaq peaked March 2000 at 5,049, bottomed Oct 2002 at 1,114 (-78%). High-multiple tech lost 90-100%. No V-shape recovery — bear lasted 2.5 years. Pattern: when P/E ratios are 100x+, mean reversion is brutal. Tech equivalents of 2000 went to zero. Today's signal: Nasdaq P/E > 35 = elevated risk.",
        "importance": 8,
        "tags": ["crash_history", "us_stocks", "risk_off", "ten_year_high", "recession_risk"],
    },
    {
        "category": "crash_history",
        "market": "all",
        "title": "1987 Black Monday — Circuit Breaker Origin",
        "content": "Oct 19, 1987: Dow -22.6% in one day — still the largest single-day % drop. Caused by portfolio insurance (automated selling) feedback loop. Recovery took 2 years. Today: circuit breakers halt trading at 7%, 13%, 20% drops. Flash crashes can still trigger 5-8% moves in minutes. Wide bid-ask spreads during crashes amplify losses.",
        "importance": 7,
        "tags": ["crash_history", "risk_off", "vix_extreme", "crisis_volatility"],
    },
    {
        "category": "crash_history",
        "market": "crypto",
        "title": "2022 Crypto Winter — Full Playbook",
        "content": "BTC fell from $69k (Nov 2021) to $15.5k (Nov 2022) = -78%. Triggered by: LUNA collapse (May 2022, -99% in 3 days), 3AC insolvency, Celsius/Voyager bankruptcy, FTX collapse (Nov 2022). Contagion spread via shared collateral. Pattern: in crypto bear markets, 80% drawdowns last 12-18 months. Never average down into contagion.",
        "importance": 9,
        "tags": ["crash_history", "crypto", "risk_off", "contagion_risk", "crypto_bearish"],
    },
    {
        "category": "crash_history",
        "market": "crypto",
        "title": "LUNA/Terra Collapse — Stablecoin Depeg Risk",
        "content": "May 2022: LUNA fell from $80 to $0.00001 in 7 days. UST (algorithmic stablecoin) lost $1 peg — death spiral. $40B market cap evaporated. Contagion: 3AC had $600M LUNA exposure — insolvency — BTC sell-off. Rule: algorithmic stablecoins carry 99% loss risk. UST depeg caused immediate BTC -25% in 48 hours.",
        "importance": 9,
        "tags": ["crash_history", "crypto", "risk_off", "contagion_risk", "crypto_bearish"],
    },
    {
        "category": "crash_history",
        "market": "crypto",
        "title": "FTX Collapse — Exchange Counterparty Risk",
        "content": "Nov 2022: FTX ($32B exchange) collapsed in 72 hours after Binance withdrew support. BTC fell 25% in 72 hours. Contagion: BlockFi, Genesis, Gemini Earn affected. Warning signs: exchange token concentrated in balance sheet, circular ownership. Rule: never leave more than 1 month's trading capital on any single exchange.",
        "importance": 9,
        "tags": ["crash_history", "crypto", "risk_off", "contagion_risk", "crypto_regulatory"],
    },
    {
        "category": "crash_history",
        "market": "all",
        "title": "2022 Rate Hike Bear Market",
        "content": "Fed raised rates 425bps in 12 months (fastest since 1980). Nasdaq -33%, S&P500 -19%, bonds -15% (worst bond year since 1788). DXY +16%. Energy +60% (only sector positive). BTC -65%. Pattern: rate hike cycle — growth/tech down, value/energy/commodities up. Rate hikes end only when something breaks (SVB 2023).",
        "importance": 9,
        "tags": ["crash_history", "risk_off", "rate_hike_cycle", "ten_year_high", "dxy_high", "crypto_bearish"],
    },
    {
        "category": "crash_history",
        "market": "all",
        "title": "Asian Financial Crisis 1997",
        "content": "July 1997: Thai baht collapsed. Spread to Indonesia, South Korea, Malaysia. DXY spiked, EM currencies fell 30-80%. Stock markets fell 50-80%. Pattern: when DXY rises rapidly, EM assets (India, Brazil, SE Asia) face currency AND equity dual losses. DXY > 105 = be cautious on EM/India.",
        "importance": 7,
        "tags": ["crash_history", "risk_off", "dxy_high", "india_stocks", "geopolitical_risk"],
    },
    {
        "category": "crash_history",
        "market": "us_stocks",
        "title": "2023 SVB Regional Bank Crisis",
        "content": "March 2023: Silicon Valley Bank failed in 48 hours after depositor run. Contagion: Signature Bank, First Republic failed within 2 weeks. KRE (regional bank ETF) fell 30%. Fed had to create BTFP emergency backstop. Pattern: bank failures spread fear — market sell-off 5-15%, then Fed backstop — recovery. Watch bank sector stress as systemic signal.",
        "importance": 8,
        "tags": ["crash_history", "us_stocks", "risk_off", "contagion_risk", "rate_hike_cycle"],
    },
    {
        "category": "crash_history",
        "market": "forex",
        "title": "1992 Black Wednesday — GBP Soros Trade",
        "content": "Sept 16, 1992: George Soros broke the Bank of England, shorting GBP vs DEM. UK forced to withdraw from ERM. GBP fell 15% in one day. Soros made $1B. Lesson: central bank defense of currency pegs can be overwhelmed by speculative capital. When a peg breaks, the move is 10-25% minimum.",
        "importance": 7,
        "tags": ["crash_history", "forex", "geopolitical_risk", "risk_off"],
    },
    {
        "category": "crash_history",
        "market": "crypto",
        "title": "2021 China Crypto Ban — Regulatory Shock",
        "content": "May 2021: China banned crypto mining and transactions. BTC fell from $59k to $30k in 3 weeks (-49%). Then recovered to $69k by November. Pattern: regulatory shock = sharp 30-50% drawdown in 2-3 weeks, then gradual recovery if fundamentals intact. China ban removed 65% of mining hashrate — network survived, price recovered.",
        "importance": 8,
        "tags": ["crash_history", "crypto", "risk_off", "crypto_regulatory", "crypto_bearish"],
    },
    {
        "category": "crash_history",
        "market": "all",
        "title": "Flash Crash May 2010",
        "content": "May 6, 2010: Dow fell 1000 points (9%) in 10 minutes, recovered 70% in 20 minutes. Caused by algorithmic trading cascade + quote stuffing. Accenture briefly went to $0.01. Lesson: flash crashes are opportunities if you have limit orders below market. Never use market orders during high volatility.",
        "importance": 7,
        "tags": ["crash_history", "us_stocks", "vix_extreme", "crisis_volatility"],
    },
    {
        "category": "crash_history",
        "market": "crypto",
        "title": "Mt. Gox Hack 2014 — Exchange Hack Pattern",
        "content": "Feb 2014: Mt. Gox (handling 70% of BTC trades) was hacked — 850k BTC stolen. BTC fell from $800 to $113 (-86%) over 12 months. Pattern: major exchange hack = immediate 20-40% BTC drop, then multi-month grinding bear market. On-chain metric: exchange BTC outflows spike before hack is public.",
        "importance": 8,
        "tags": ["crash_history", "crypto", "risk_off", "contagion_risk", "crypto_bearish"],
    },
    {
        "category": "crash_history",
        "market": "all",
        "title": "Oil Shock Recessions — Historical Pattern",
        "content": "1973 OPEC oil embargo — US recession. 1979 Iranian Revolution — stagflation. 1990 Iraq-Kuwait — mild recession. 2008 oil at $147 preceded GFC peak. Pattern: oil price doubling from trough within 12 months precedes recession 80% of time. Current oil > $100 with already-high rates = elevated recession risk.",
        "importance": 7,
        "tags": ["crash_history", "oil_spike", "recession_risk", "risk_off", "geopolitical_risk"],
    },
    {
        "category": "crash_history",
        "market": "crypto",
        "title": "2018 ICO Bust — Altcoin Cycle Pattern",
        "content": "Jan 2018: crypto total market cap fell from $800B to $100B (-87%) by Dec 2018. Most ICO coins fell 95-99%. BTC fell 84%, ETH fell 94%. Pattern: after a parabolic altcoin run, the correction is always 80-95% from peak. Altcoins always fall faster and further than BTC. In a crypto bear market, only BTC and ETH have a real floor.",
        "importance": 8,
        "tags": ["crash_history", "crypto", "risk_off", "crypto_bearish", "extreme_fear"],
    },
    {
        "category": "crash_history",
        "market": "all",
        "title": "Lehman Contagion Sequence — Systemic Risk",
        "content": "Sept 15, 2008: Lehman files Chapter 11. Sequence: money market fund breaks the buck — commercial paper freezes — TED spread spikes to 4.65% — coordinated global central bank intervention. Pattern: if TED spread > 2%, systemic risk is elevated. Crypto equivalent: if a top-5 exchange halts withdrawals, assume contagion.",
        "importance": 8,
        "tags": ["crash_history", "risk_off", "vix_extreme", "contagion_risk", "recession_risk"],
    },
    {
        "category": "crash_history",
        "market": "all",
        "title": "COVID Yield Curve Control — Japan Pattern",
        "content": "2022-2023: Bank of Japan maintained yield curve control (YCC) while rest of world raised rates. JPY fell 30% vs USD. BoJ eventually forced to widen the band (Dec 2022, July 2023). Pattern: artificially suppressed yields — currency devaluation — eventual policy capitulation = large JPY moves (5-8% in a day when YCC breaks).",
        "importance": 6,
        "tags": ["crash_history", "forex", "rate_hike_cycle", "geopolitical_risk"],
    },

    # ── Macro Regime (20 entries) ─────────────────────────────────────────────
    {
        "category": "macro_regime",
        "market": "all",
        "title": "Rate Hike Cycle Playbook",
        "content": "Fed hiking: growth stocks -30-50% (duration assets devalued), financials +10-20% (net interest margin expands), energy/commodities +20-40%, bonds -10-25%, dollar strengthens. Phase 1 (first 3 hikes): denial rally, then drop. Phase 2 (hiking continues): sustained bear. Phase 3 (pause signal): sharp bear market rally 10-20%. Only buy the real pivot, not rumors.",
        "importance": 9,
        "tags": ["macro_regime", "rate_hike_cycle", "ten_year_high", "dxy_high", "risk_off"],
    },
    {
        "category": "macro_regime",
        "market": "all",
        "title": "Rate Cut Cycle Playbook",
        "content": "Fed cutting: growth stocks +30-60% over 12-18 months, gold +15-25%, bonds +10-20%, dollar weakens. But: if cuts happen because of recession, first move is DOWN before up. Average time from first cut to S&P500 bottom: 6 months. Crypto typically lags equities by 2-4 months at start of cut cycle but leads at end.",
        "importance": 9,
        "tags": ["macro_regime", "rate_cut_cycle", "ten_year_low", "dxy_low", "crypto_bullish"],
    },
    {
        "category": "macro_regime",
        "market": "all",
        "title": "Yield Curve Inversion — Recession Signal",
        "content": "When 2Y Treasury yield > 10Y Treasury yield (inverted curve), recession follows in 6-18 months with 85% historical accuracy. Inversion of 2023 was deepest since 1981 (-100bps). Once curve uninverts, recession usually starts within 6 months. Pattern: sell risk assets when curve uninverts, not when it first inverts.",
        "importance": 9,
        "tags": ["macro_regime", "recession_risk", "rate_hike_cycle", "ten_year_high", "risk_off", "yield_curve_inverted"],
    },
    {
        "category": "macro_regime",
        "market": "all",
        "title": "DXY Strength — EM and Crypto Impact",
        "content": "DXY (Dollar Index) above 105: EM equities fall 10-20%, commodities fall 5-15%, crypto falls 15-25%. Above 108: EM currency crisis risk. Mechanism: dollar strength = capital flight from EM, dollar-denominated debts become harder to service. India (Nifty) has -0.6 correlation with DXY. Strong dollar = structural headwind for everything non-dollar.",
        "importance": 9,
        "tags": ["macro_regime", "dxy_high", "risk_off", "india_stocks", "crypto_bearish"],
    },
    {
        "category": "macro_regime",
        "market": "all",
        "title": "VIX Regime Classification",
        "content": "VIX < 15: complacency, trending market, normal sizing. VIX 15-20: normal volatility. VIX 20-30: caution, reduce leverage 25%. VIX 30-40: fear, reduce leverage 50%, tighten stops. VIX 40-60: panic, reduce to 25% sizing, only scalps. VIX > 60 (2008/2020 levels): cash is king, only tiny positions, wait for VIX to peak and roll over.",
        "importance": 9,
        "tags": ["macro_regime", "vix_high", "vix_extreme", "crisis_volatility", "risk_off"],
    },
    {
        "category": "macro_regime",
        "market": "all",
        "title": "Stagflation Environment — 1970s Pattern",
        "content": "Stagflation = high inflation + low growth. Worst environment for both stocks and bonds simultaneously. Best assets: gold, oil, commodities, real assets. Worst: long-duration bonds, growth tech, consumer discretionary. 1973-82: gold +500%, oil +700%, S&P500 flat in real terms. Current signal: if CPI > 6% AND GDP < 1% = stagflation watch.",
        "importance": 8,
        "tags": ["macro_regime", "oil_high", "gold_high", "risk_off", "rate_hike_cycle", "recession_risk"],
    },
    {
        "category": "macro_regime",
        "market": "all",
        "title": "Soft Landing vs Hard Landing",
        "content": "Soft landing (Fed raises rates, inflation falls, no recession): risk assets rally. Hard landing (Fed overtightens, recession): risk assets fall 20-40% more. Historical base rate for soft landing: 30%. After most hiking cycles, hard landing occurs. Signs of soft landing: unemployment stays < 4.5%, GDP stays positive, inflation cools. Watch monthly NFP.",
        "importance": 8,
        "tags": ["macro_regime", "rate_hike_cycle", "recession_risk", "nfp_event"],
    },
    {
        "category": "macro_regime",
        "market": "all",
        "title": "QE vs QT Impact on Markets",
        "content": "QE (Fed buying assets): money supply expands — stocks, crypto, bonds all rally. Fed balance sheet expansion of $1T historically correlates with S&P500 +15-20%. QT (Fed selling assets): opposite — liquidity drain causes all risk assets to fall. BTC has 0.85 correlation with Fed balance sheet size. Monitor Fed H.4.1 weekly release.",
        "importance": 8,
        "tags": ["macro_regime", "rate_cut_cycle", "crypto_bullish", "risk_on"],
    },
    {
        "category": "macro_regime",
        "market": "all",
        "title": "Gold as Safe Haven — Conditions",
        "content": "Gold rises in: (1) dollar weakness, (2) negative real rates (nominal rate < inflation), (3) geopolitical crisis, (4) financial system stress. Gold falls in: (1) dollar strength, (2) positive real rates. Gold above $2000: positive momentum. Above $2500: possible parabolic. Gold does not pay yield so rising real rates are its biggest enemy.",
        "importance": 7,
        "tags": ["macro_regime", "gold_high", "risk_off", "geopolitical_risk", "dxy_low"],
    },
    {
        "category": "macro_regime",
        "market": "all",
        "title": "Oil Price — Economic Impact",
        "content": "Oil above $90: mild headwind for consumers. Above $100: recessionary risk, airline/shipping stocks fall, energy stocks rally. Above $120: stagflation risk, Fed forced to choose between fighting inflation and supporting growth. Below $60: deflationary signal, energy sector hit, Saudi Arabia production cuts likely.",
        "importance": 8,
        "tags": ["macro_regime", "oil_high", "oil_spike", "risk_off", "geopolitical_risk"],
    },
    {
        "category": "macro_regime",
        "market": "all",
        "title": "Recession Indicators — Early Warning",
        "content": "Top 3 recession leading indicators: (1) yield curve inversion (leads by 6-18 months), (2) ISM Manufacturing PMI below 50 for 3+ months, (3) LEI (Leading Economic Index) falling for 6+ consecutive months. Secondary: jobless claims rising, consumer confidence falling. When all 3 trigger simultaneously: 90% probability of recession within 12 months.",
        "importance": 9,
        "tags": ["macro_regime", "recession_risk", "risk_off", "yield_curve_inverted"],
    },
    {
        "category": "macro_regime",
        "market": "all",
        "title": "Reflationary Cycle — Recovery Pattern",
        "content": "Post-recession recovery: (1) small cap stocks lead first (+30-50% before large caps), (2) cyclicals outperform defensives, (3) emerging markets rally as dollar weakens, (4) crypto bull cycle begins. Historical reflationary cycle: 18-24 months. Most profitable phase: first 12 months after recession bottom. Signal: S&P500 breaks above 200-day moving average.",
        "importance": 8,
        "tags": ["macro_regime", "risk_on", "rate_cut_cycle", "dxy_low", "crypto_bullish"],
    },
    {
        "category": "macro_regime",
        "market": "crypto",
        "title": "Crypto in Risk-Off Environments",
        "content": "In Risk-Off regimes, BTC correlation with Nasdaq increases to 0.8+. Crypto is treated as a risk asset by institutions — they sell crypto first. However, extreme risk-off (bank failures, dollar devaluation fears) can trigger crypto rally as hedge against system failure. Standard risk-off = sell crypto; systemic banking crisis = crypto potentially bullish.",
        "importance": 9,
        "tags": ["macro_regime", "crypto", "risk_off", "vix_high"],
    },
    {
        "category": "macro_regime",
        "market": "all",
        "title": "Dollar Milkshake Theory",
        "content": "In global crises, dollar strengthens as global debt (denominated in dollars) must be repaid, creating forced buying pressure. DXY can rise 15-25% in crisis years (2008: +12%, 2020: +8%, 2022: +16%). During dollar spikes: EM currencies crisis, commodities fall, crypto falls. But post-crisis: dollar retreats — all assets recover.",
        "importance": 7,
        "tags": ["macro_regime", "dxy_high", "risk_off", "contagion_risk"],
    },
    {
        "category": "macro_regime",
        "market": "all",
        "title": "Inflation Regimes — Asset Class Performance",
        "content": "Low inflation (< 2%): growth stocks outperform, bonds safe, crypto can thrive. Moderate inflation (2-4%): stocks generally fine, value beats growth, commodities good. High inflation (4-8%): real assets win (commodities, gold, REITs), bonds lose, cash erodes. Hyperinflation (> 10%): only tangible assets/crypto safe, fiat cash loses value rapidly.",
        "importance": 8,
        "tags": ["macro_regime", "rate_hike_cycle", "gold_high", "oil_high", "risk_off"],
    },
    {
        "category": "macro_regime",
        "market": "all",
        "title": "Election Year Market Patterns",
        "content": "US Presidential election years: S&P500 average return +11.6% vs +7% in non-election years. H1 often weak as uncertainty persists, H2 rallies post-election (regardless of winner). Incumbent party tends toward market-friendly policies to boost economy. Pattern: buy equities in October of election year, sell in January of post-election year.",
        "importance": 6,
        "tags": ["macro_regime", "geopolitical_risk", "us_stocks"],
    },
    {
        "category": "macro_regime",
        "market": "all",
        "title": "Global Liquidity Cycle",
        "content": "Global central bank balance sheets (Fed + ECB + BOJ + PBOC) combined ~$24T. When all are expanding simultaneously — risk assets rally globally. When all contract — global risk-off. China PBOC injections are particularly important for crypto and EM. Watch M2 money supply growth: above 8% = bullish for risk, below 2% = bearish.",
        "importance": 7,
        "tags": ["macro_regime", "risk_on", "crypto_bullish", "rate_cut_cycle"],
    },
    {
        "category": "macro_regime",
        "market": "all",
        "title": "Credit Spreads as Stress Indicator",
        "content": "High-yield (junk bond) credit spreads vs Treasuries: < 300bps = calm. 300-500bps = caution. 500-800bps = stress. > 800bps = crisis. Investment grade spreads: < 100bps = normal, > 200bps = stress. Credit markets lead equity markets by 2-4 weeks. If spreads are widening while stocks are flat, sell stocks — credit is telling the truth.",
        "importance": 8,
        "tags": ["macro_regime", "risk_off", "recession_risk", "contagion_risk"],
    },
    {
        "category": "macro_regime",
        "market": "all",
        "title": "Commodity Supercycle",
        "content": "Commodity supercycles last 15-20 years. Energy transition (EVs, solar) drives demand for copper, lithium, nickel. Oil capex underinvestment means supply constrained. Pattern: commodity supercycles benefit Brazil, Australia, Canada, India (metals exporters). Crypto mining costs are linked to energy prices — oil spike = higher mining cost floor.",
        "importance": 6,
        "tags": ["macro_regime", "oil_high", "gold_high", "macro_cycle"],
    },
    {
        "category": "macro_regime",
        "market": "all",
        "title": "China Economic Cycles — Global Impact",
        "content": "China GDP growth directly impacts: iron ore, copper, coal, luxury goods, semiconductors. China slowdown = EM selloff, commodities fall. China stimulus = EM rally, commodities rise. Chinese New Year (Jan-Feb): crypto historically rallies as Chinese retail participates. China PMI > 50 = global reflation signal.",
        "importance": 7,
        "tags": ["macro_regime", "geopolitical_risk", "macro_cycle", "risk_on"],
    },

    # ── Sector Rotation (15 entries) ─────────────────────────────────────────
    {
        "category": "sector_rotation",
        "market": "us_stocks",
        "title": "Sector Rotation Wheel — Full Cycle",
        "content": "Economic cycle rotates: Recovery (small caps, financials, tech lead) — Expansion (tech, consumer discretionary) — Peak (energy, materials, industrials) — Slowdown (healthcare, utilities, consumer staples) — Recession (bonds, gold, utilities) — Recovery (cycle repeats). Current regime determines which sector to favour. Average full cycle: 7-10 years.",
        "importance": 8,
        "tags": ["sector_rotation", "us_stocks", "macro_cycle"],
    },
    {
        "category": "sector_rotation",
        "market": "us_stocks",
        "title": "Tech in Rate Hike Cycles",
        "content": "Technology stocks are long-duration assets. Rising rates compress P/E multiples. Rule: each 100bps rise in 10Y yield — tech P/E contracts 15-25%. In 2022, Nasdaq fell 33% as rates rose 425bps. Tech rallies when rates peak and start falling. Signal to buy tech: 10Y yield breaks below its 50-day moving average.",
        "importance": 9,
        "tags": ["sector_rotation", "us_stocks", "rate_hike_cycle", "ten_year_high"],
    },
    {
        "category": "sector_rotation",
        "market": "us_stocks",
        "title": "Energy Sector vs Oil Price",
        "content": "Energy stocks (XLE) have 0.85 correlation with WTI crude. Oil above $80: energy sector outperforms. Oil above $90: energy is the only sector that rallies in risk-off. Oil below $50: energy stocks fall 30-40%. Integrated majors move 60-70% of oil price change. Service companies move 80-100%. E&P companies leverage oil 1.5-2x.",
        "importance": 7,
        "tags": ["sector_rotation", "us_stocks", "oil_high", "oil_spike"],
    },
    {
        "category": "sector_rotation",
        "market": "us_stocks",
        "title": "Financials in Rate Hike Cycles",
        "content": "Banks benefit from rate hikes (higher net interest margins) — BUT only in early hike cycle. If hikes cause recession, bank credit losses negate the NIM benefit. Phase 1 (first 6 months of hiking): buy banks. Phase 2 (extended hiking): sell banks (recession risk rises). Regional banks most sensitive — less diversification than money-center banks.",
        "importance": 7,
        "tags": ["sector_rotation", "us_stocks", "rate_hike_cycle", "recession_risk"],
    },
    {
        "category": "sector_rotation",
        "market": "us_stocks",
        "title": "Defensive Sectors in Recession",
        "content": "Recession playbook: BUY: consumer staples (P&G, Walmart), utilities, healthcare, pharma, gold miners. SELL: consumer discretionary, industrials, materials, small caps. Consumer staples fell only 5% in 2008 vs S&P500 -57%. Utilities fell 30% (still bad, but dividend cushion helps). Healthcare was flat. These rotate in 3-6 months before economic data confirms recession.",
        "importance": 8,
        "tags": ["sector_rotation", "us_stocks", "recession_risk", "risk_off", "gold_high"],
    },
    {
        "category": "sector_rotation",
        "market": "us_stocks",
        "title": "REITs — Rate Sensitivity",
        "content": "REITs are the most rate-sensitive sector. 10Y yield rising 100bps — REITs fall 15-25%. Rising rates increase REIT financing costs AND make their dividend yields less attractive vs risk-free rate. In rate cut cycle: REITs outperform S&P500 by 20-30% over 2 years. Buy REITs when 10Y yield peaks.",
        "importance": 7,
        "tags": ["sector_rotation", "us_stocks", "rate_hike_cycle", "ten_year_high", "rate_cut_cycle"],
    },
    {
        "category": "sector_rotation",
        "market": "us_stocks",
        "title": "Semiconductors — Leading Indicator",
        "content": "Semiconductor stocks (SOXX) are the leading indicator for the broader tech sector and the economy. They peak 6-9 months before the broad market. When SOXX breaks below its 200-day MA while Nasdaq is still near highs: sell tech within 3 months. SOXX also leads the recovery — buy SOXX when it breaks above 200-day MA in a bear market.",
        "importance": 7,
        "tags": ["sector_rotation", "us_stocks", "macro_cycle"],
    },
    {
        "category": "sector_rotation",
        "market": "us_stocks",
        "title": "Small Cap vs Large Cap Rotation",
        "content": "Small caps (IWM) outperform in: early recovery, risk-on, domestic-focused economy, weak dollar. Large caps (SPY) outperform in: risk-off, late cycle, strong dollar, global slowdown. Rule: when DXY falls, rotate from large to small. When DXY rises, rotate to large. Small caps are also more sensitive to credit conditions.",
        "importance": 7,
        "tags": ["sector_rotation", "us_stocks", "risk_on", "risk_off", "dxy_high", "dxy_low"],
    },
    {
        "category": "sector_rotation",
        "market": "us_stocks",
        "title": "Healthcare — Defensive with Growth",
        "content": "Healthcare is defensive (lower beta) but has secular growth tailwind from aging demographics. Pharma outperforms in recession. Biotech is speculative growth — correlates with Nasdaq, underperforms in rate hikes. For defensive positioning: large-cap pharma + managed care (UNH) over biotech.",
        "importance": 6,
        "tags": ["sector_rotation", "us_stocks", "recession_risk", "risk_off"],
    },
    {
        "category": "sector_rotation",
        "market": "india_stocks",
        "title": "India IT Sector — Dollar Dependence",
        "content": "India IT exports (TCS, Infosys, Wipro) earn in USD but report in INR. Strong dollar = higher INR revenues. US slowdown = IT spending cuts = IT sector falls 15-30%. Indian IT tracks Nasdaq with 3-6 month lag. When US companies cut IT budgets (watch Microsoft guidance), India IT follows. Nifty IT has 0.75 correlation with Nasdaq.",
        "importance": 7,
        "tags": ["sector_rotation", "india_stocks", "us_stocks", "dxy_high"],
    },
    {
        "category": "sector_rotation",
        "market": "india_stocks",
        "title": "India FMCG — Defensive in Volatility",
        "content": "India FMCG (Hindustan Unilever, Nestle, Dabur) — classic defensive sector. Outperforms in monsoon failures, rate hike cycles, global risk-off. HUL has beta of 0.45 vs Nifty. Buy FMCG when FII outflows accelerate, sell when economy recovering. FMCG valuations are expensive normally — watch P/E vs historical average.",
        "importance": 6,
        "tags": ["sector_rotation", "india_stocks", "risk_off", "recession_risk"],
    },
    {
        "category": "sector_rotation",
        "market": "india_stocks",
        "title": "India Metals — China Proxy",
        "content": "India metals (Tata Steel, Hindalco, SAIL) closely track Chinese demand and global commodity prices. Steel: tracks iron ore + coking coal. Aluminium: tracks LME aluminium + energy costs. When China stimulates infrastructure: India metals rally 20-40%. When global slowdown: metals fall first (leading indicator for Indian economy).",
        "importance": 6,
        "tags": ["sector_rotation", "india_stocks", "oil_high", "geopolitical_risk"],
    },
    {
        "category": "sector_rotation",
        "market": "us_stocks",
        "title": "Gold Miners vs Physical Gold",
        "content": "Gold miners (GDX, GDXJ) provide 2-3x leverage to gold price moves. Gold up 10% — GDX up 20-30%. But miners have operational risk, hedging, political risk (mines in EM countries). Junior miners (GDXJ) are most volatile — 4-5x gold leverage. In gold bear market: miners fall 50-70% vs gold -20-30%. Use miners only in confirmed gold bull trend.",
        "importance": 6,
        "tags": ["sector_rotation", "us_stocks", "gold_high", "gold_spike", "risk_off"],
    },
    {
        "category": "sector_rotation",
        "market": "us_stocks",
        "title": "Consumer Discretionary — Cycle Sensitivity",
        "content": "Consumer discretionary (retail, restaurants, luxury, autos) is the most cyclically sensitive sector. Unemployment rising 1% = consumer discretionary falls 15-20%. Best performers in early-mid expansion when consumer confidence is high and employment is rising. Avoid in late-cycle when credit card debt is high and savings are low.",
        "importance": 6,
        "tags": ["sector_rotation", "us_stocks", "recession_risk", "risk_off"],
    },
    {
        "category": "sector_rotation",
        "market": "all",
        "title": "Materials in Commodity Supercycle",
        "content": "Materials sector (copper, lithium, nickel, rare earths) benefits from energy transition. Electric vehicles require 4x more copper than ICE vehicles. Grid expansion for renewables requires massive copper and steel. Companies: Freeport-McMoRan (copper), Albemarle (lithium), Vale (iron ore/nickel). Supply constraints make these defensive in inflation.",
        "importance": 6,
        "tags": ["sector_rotation", "us_stocks", "macro_cycle", "oil_high"],
    },

    # ── Geopolitical (12 entries) ─────────────────────────────────────────────
    {
        "category": "geopolitical",
        "market": "all",
        "title": "Middle East Conflict — Oil Spike Pattern",
        "content": "Middle East tensions — oil price spike pattern: announcement day +5-10%, then fade if supply not disrupted. If Strait of Hormuz threatened (20% of global oil): immediate +20-30% spike. Beneficiaries: energy stocks, defense contractors, gold. Losers: airlines, shipping, consumer discretionary. If war contained: 2-4 week spike then fade.",
        "importance": 8,
        "tags": ["geopolitical", "oil_spike", "oil_high", "risk_off", "geopolitical_risk"],
    },
    {
        "category": "geopolitical",
        "market": "all",
        "title": "Russia-Ukraine War — Commodity Shock",
        "content": "Feb 2022: Russia invaded Ukraine. Immediate impact: natural gas +200%, wheat +50%, nickel +100% in days, grain exports blocked. Oil rose from $80 to $130. Gold initially sold (liquidity), then rose. Duration: commodity prices stayed elevated 12+ months. Russia sanctions disrupted global trade patterns significantly.",
        "importance": 8,
        "tags": ["geopolitical", "oil_spike", "gold_high", "risk_off", "geopolitical_risk"],
    },
    {
        "category": "geopolitical",
        "market": "us_stocks",
        "title": "US-China Trade War — Semiconductor Impact",
        "content": "2018-2019 US-China trade war: tariffs on $360B goods. Tech hardware fell 15-20% (supply chain in China). 2022-2023: chip export controls. NVIDIA banned from selling H100s to China. TSMC (Taiwan) critical chokepoint — 90% of advanced chips. Geopolitical risk premium for Taiwan: TSMC and Apple face major disruption if tensions spike.",
        "importance": 8,
        "tags": ["geopolitical", "us_stocks", "geopolitical_risk", "risk_off"],
    },
    {
        "category": "geopolitical",
        "market": "all",
        "title": "Sanctions Impact on Markets",
        "content": "Western sanctions on Russia (2022) removed Russian oil/gas from global markets, raised energy prices. Sanctions on Iran removed 1-2M barrels/day of oil. Effective sanctions — commodity price spikes in targeted sector. SWIFT exclusions are the maximum financial weapon — cutting a country off from dollar system causes immediate currency collapse.",
        "importance": 7,
        "tags": ["geopolitical", "oil_high", "geopolitical_risk", "risk_off"],
    },
    {
        "category": "geopolitical",
        "market": "all",
        "title": "Taiwan Risk — Semiconductor Black Swan",
        "content": "Taiwan produces 90% of world's advanced semiconductors (TSMC). Military conflict over Taiwan = global chip shortage lasting 2-5 years. Apple, NVIDIA, AMD would face existential supply problems. Stock market impact estimated at -30-50% for tech sector. Insurance: own physical gold, avoid semiconductor-dependent tech. Low probability but civilization-scale impact.",
        "importance": 7,
        "tags": ["geopolitical", "us_stocks", "geopolitical_risk", "risk_off", "contagion_risk"],
    },
    {
        "category": "geopolitical",
        "market": "all",
        "title": "Election Year Volatility Pattern",
        "content": "In election years: volatility increases Sept-Oct as uncertainty peaks, then falls post-election (regardless of winner). VIX historically +20-30% in the month before election, then -25% in the month after. Currency volatility also spikes around elections. Both US and India elections create 2-4% index moves.",
        "importance": 6,
        "tags": ["geopolitical", "geopolitical_risk", "vix_high", "high_impact_event"],
    },
    {
        "category": "geopolitical",
        "market": "crypto",
        "title": "Crypto Regulatory Shocks — Country Bans",
        "content": "Country crypto ban pattern: announcement — -20-40% BTC in 2-4 weeks — recovery if rest of world does not follow. China's 2021 ban: -50% BTC, then +130% recovery. India's threatened ban: -30% INR-denominated crypto in 2022. Key insight: country bans cannot stop the network, only slow adoption. Decentralization is anti-fragile to country-level regulation.",
        "importance": 8,
        "tags": ["geopolitical", "crypto", "crypto_regulatory", "risk_off"],
    },
    {
        "category": "geopolitical",
        "market": "india_stocks",
        "title": "India-Pakistan Tensions — Market Impact",
        "content": "India-Pakistan military tensions historically cause Nifty to fall 3-8% in first 2 days, then recover as situation stabilizes. 2019 Pulwama: Nifty -0.8% (muted reaction, no direct war). 2001-02 standoff: Nifty -15% over 3 months. Defense stocks rally. INR weakens 2-4% vs dollar. Foreign investors exit — watch FII selling data.",
        "importance": 6,
        "tags": ["geopolitical", "india_stocks", "geopolitical_risk", "risk_off"],
    },
    {
        "category": "geopolitical",
        "market": "all",
        "title": "Central Bank Independence Threats",
        "content": "When politicians threaten central bank independence: currency falls 5-15%, bond yields spike, stocks fall 5-10%. Example: Turkey 2021 (Erdogan fired central bank governors) — lira fell 44% in 1 year. US equivalent: if Fed independence threatened, dollar would lose reserve currency status = catastrophic tail risk.",
        "importance": 7,
        "tags": ["geopolitical", "geopolitical_risk", "risk_off", "forex", "rate_hike_cycle"],
    },
    {
        "category": "geopolitical",
        "market": "all",
        "title": "Energy Security — Geopolitical Premium",
        "content": "Countries dependent on Russian gas (Germany, Italy) faced crisis in 2022. Energy security = geopolitical leverage. Strategic petroleum reserve (SPR) releases can cool oil prices short-term (-$10-15/barrel). Long-term: energy transition reduces oil geopolitical risk but increases critical minerals risk (lithium from Chile, cobalt from DRC).",
        "importance": 6,
        "tags": ["geopolitical", "oil_high", "oil_spike", "geopolitical_risk"],
    },
    {
        "category": "geopolitical",
        "market": "crypto",
        "title": "Geopolitical Conflict — Crypto as Refuge",
        "content": "In active war zones, Bitcoin becomes store of value for citizens. Ukraine 2022: $100M+ in crypto donations received. Russia: citizens bought crypto as ruble collapsed. Paradox: geopolitical conflict is bearish for crypto short-term (risk-off), but creates long-term adoption in affected countries. If conflict involves major economy, crypto falls with all risk assets initially.",
        "importance": 6,
        "tags": ["geopolitical", "crypto", "geopolitical_risk", "risk_off"],
    },
    {
        "category": "geopolitical",
        "market": "all",
        "title": "Emerging Market Contagion Pattern",
        "content": "EM contagion sequence: weak-link country faces currency crisis — IMF bailout (or not) — investor redemptions in EM funds — selling of ALL EM assets including healthy ones. Recent: Turkey 2021, Sri Lanka 2022, Pakistan 2023. India typically sees FII selling of Rs 30-50,000 crore during EM contagion. Signal: when EM VXY spikes 20%+ — buy Indian blue chips on dip.",
        "importance": 7,
        "tags": ["geopolitical", "india_stocks", "geopolitical_risk", "risk_off", "contagion_risk", "dxy_high"],
    },

    # ── Fed Policy (15 entries) ───────────────────────────────────────────────
    {
        "category": "fed_policy",
        "market": "all",
        "title": "FOMC Week Protocol",
        "content": "FOMC meeting (8 per year): reduce all leveraged positions by 50% the day before. Post-decision: wait 30 minutes for initial fakeout move to complete before taking positions. The Fed statement + press conference last 2 hours. Powell press conference often contradicts statement — the Q&A is more market-moving than the written statement.",
        "importance": 9,
        "tags": ["fed_policy", "fomc_week", "fed_event", "high_impact_event"],
    },
    {
        "category": "fed_policy",
        "market": "all",
        "title": "CPI Print — Reaction Pattern",
        "content": "CPI higher than expected: stocks -1 to -3%, dollar +0.5%, gold -0.5-1%. CPI lower than expected: stocks +1-3%, dollar -0.5%, gold +0.5-1%. CPI in-line: stocks flat, wait for Fed reaction. Largest moves: first CPI print after a trend change. Core CPI (ex-food/energy) matters more than headline for Fed decisions.",
        "importance": 9,
        "tags": ["fed_policy", "cpi_event", "high_impact_event"],
    },
    {
        "category": "fed_policy",
        "market": "all",
        "title": "NFP — Non-Farm Payrolls Interpretation",
        "content": "NFP higher than expected: economy strong = risk of more hikes = stocks can fall, dollar rises. NFP lower than expected: economic weakness = Fed may cut = stocks rally, dollar falls. BUT: bad news is good news only if inflation is under control. In high-inflation environment, weak NFP = stocks fall (stagflation fear). Goldilocks: NFP slightly above consensus + low wage growth.",
        "importance": 9,
        "tags": ["fed_policy", "nfp_event", "high_impact_event"],
    },
    {
        "category": "fed_policy",
        "market": "all",
        "title": "Powell Pivot Language — Signal Words",
        "content": "HAWKISH: 'higher for longer', 'not yet confident inflation defeated', 'risks remain balanced'. DOVISH: 'data dependent', 'cumulative tightening', 'disinflation underway'. PIVOT SIGNAL: 'slowing pace of increases', 'appropriate to begin reducing', 'discussed rate cuts'. Historical: 6-18 months between pivot language and actual cuts. Don't front-run — wait for actual cuts.",
        "importance": 9,
        "tags": ["fed_policy", "fomc_week", "fed_event", "rate_cut_cycle"],
    },
    {
        "category": "fed_policy",
        "market": "all",
        "title": "Rate Pause vs Rate Cut — Different Impact",
        "content": "Rate pause (Fed stops hiking): stocks rally 5-15% within 3 months as hike cycle ends. But risk remains elevated as Fed says higher for longer. Rate cut (Fed actually cuts): stocks initially rally 3-5%, then may fall if cuts signal recession. Cut in anticipation of recession (2007, 2019) — markets peaked 6 months after last hike.",
        "importance": 9,
        "tags": ["fed_policy", "rate_cut_cycle", "rate_hike_cycle", "fed_event"],
    },
    {
        "category": "fed_policy",
        "market": "crypto",
        "title": "Bitcoin and Fed Policy",
        "content": "BTC has -0.85 correlation with real interest rates (10Y nominal minus inflation). When rates rise faster than inflation: BTC falls. When inflation rises faster than rates (negative real rates): BTC thrives. BTC rallied from $3k to $69k (2018-2021) during zero interest rate policy. Watch TIPS yields (real rates): below 0% = bullish BTC. Above 2% = bearish BTC.",
        "importance": 9,
        "tags": ["fed_policy", "crypto", "rate_hike_cycle", "rate_cut_cycle", "ten_year_high"],
    },
    {
        "category": "fed_policy",
        "market": "all",
        "title": "Fed Balance Sheet vs Risk Assets",
        "content": "Fed balance sheet peaked at $9T (April 2022). Each $1T reduction (QT) historically equals 3-5% S&P500 downside. QT at $95B/month = ~$1.14T/year. BTC correlation with Fed balance sheet: 0.85. When Fed stops QT (balance sheet stabilizes): signal to add risk. When Fed resumes QE (balance sheet expands): major bull signal for all risk assets.",
        "importance": 8,
        "tags": ["fed_policy", "risk_on", "risk_off", "crypto_bullish"],
    },
    {
        "category": "fed_policy",
        "market": "all",
        "title": "Jackson Hole Speech — August Signal",
        "content": "Jackson Hole symposium (late August annually): Fed Chair gives major policy speech. Markets can move 1-3% based on tone. Pivotal examples: Bernanke QE2 hint (Aug 2010) — stocks +3%. Powell 'pain' speech (Aug 2022) — stocks -5%. Pattern: Jackson Hole hawks — sells off for weeks. Jackson Hole dove — multi-month rally. Treat as equivalent to FOMC meeting.",
        "importance": 8,
        "tags": ["fed_policy", "fomc_week", "fed_event", "high_impact_event"],
    },
    {
        "category": "fed_policy",
        "market": "all",
        "title": "Emergency Fed Actions — Market Signal",
        "content": "Emergency Fed rate cuts (outside scheduled FOMC meetings): historically signal extreme stress. 2001 (9/11): -50bps emergency — massive rally. 2008: several emergency cuts — temporary rallies before resuming fall. 2020 (COVID): -150bps in 2 meetings — initial sell-off then massive rally. Pattern: emergency cut = panic sell for 1-2 days, then buy the dip as liquidity floods system.",
        "importance": 8,
        "tags": ["fed_policy", "fed_event", "crisis_volatility", "vix_extreme"],
    },
    {
        "category": "fed_policy",
        "market": "india_stocks",
        "title": "RBI vs Fed Divergence",
        "content": "When Fed hikes and RBI does not: INR weakens, FIIs sell India bonds (higher US yields), Nifty faces headwind. When both hike simultaneously: less INR impact. When Fed cuts and RBI holds: INR strengthens, FII inflows return. India has to balance domestic inflation vs currency stability vs growth. RBI pause after Fed cut = INR bullish = Nifty bullish.",
        "importance": 8,
        "tags": ["fed_policy", "india_stocks", "forex", "rate_hike_cycle", "rate_cut_cycle"],
    },
    {
        "category": "fed_policy",
        "market": "all",
        "title": "Inflation Expectations and Breakevens",
        "content": "5Y5Y inflation swap (market inflation expectation for 5 years, starting 5 years from now): above 2.5% = Fed likely to stay hawkish. Below 2% = potential for dovish pivot. TIPS breakevens (difference between nominal 10Y and TIPS 10Y): above 2.5% = inflation fears elevated. Below 2% = deflation risk. These lead Fed policy by 3-6 months.",
        "importance": 7,
        "tags": ["fed_policy", "rate_hike_cycle", "ten_year_high"],
    },
    {
        "category": "fed_policy",
        "market": "all",
        "title": "PCE Deflator — Fed's Preferred Measure",
        "content": "Fed targets 2% PCE deflator (not CPI). PCE runs 0.2-0.5% below CPI historically. Core PCE (excludes food/energy) is what Fed focuses on. When Core PCE > 3%: no cuts. Between 2-3%: possibly preparing to cut. Below 2%: cutting or considering cutting. Core PCE falling faster than expected = strong buy signal for rate-sensitive assets.",
        "importance": 8,
        "tags": ["fed_policy", "rate_cut_cycle", "cpi_event"],
    },
    {
        "category": "fed_policy",
        "market": "all",
        "title": "ISM Manufacturing vs Fed Policy",
        "content": "ISM Manufacturing PMI: 50+ = expansion, below 50 = contraction. Below 50 for 3+ months = pressure on Fed to cut rates. During 2022-2023: ISM fell below 50 for 16 months yet Fed kept hiking due to high inflation. Once inflation falls to 3% and ISM < 48: strong case for rate cuts. Historically, first rate cut comes 3-6 months after ISM bottoms.",
        "importance": 7,
        "tags": ["fed_policy", "rate_cut_cycle", "recession_risk"],
    },
    {
        "category": "fed_policy",
        "market": "all",
        "title": "Reverse Repo Market — Liquidity Barometer",
        "content": "Fed Overnight Reverse Repo (RRP): when banks park excess cash here (>$1T), it signals abundant liquidity. When RRP drains to near zero, it signals potential liquidity stress. RRP peaked at $2.5T in 2022-2023, then drained. When RRP = $0, liquidity conditions become similar to 2019 (repo market stress). Watch RRP weekly data — below $200B = caution.",
        "importance": 6,
        "tags": ["fed_policy", "risk_off", "contagion_risk"],
    },
    {
        "category": "fed_policy",
        "market": "all",
        "title": "Dot Plot — Fed Rate Projections",
        "content": "Fed dot plot (released quarterly with FOMC meetings): shows each Fed official rate projection. Market watches median dot for policy signals. When median dot revised UP: rates going higher than expected — sell risk. When revised DOWN: pivot approaching — buy risk. Short-term (next 2 meetings): fairly reliable. Do not rely on 2-year dot plot accuracy.",
        "importance": 7,
        "tags": ["fed_policy", "fomc_week", "fed_event"],
    },

    # ── Crypto Specific (25 entries) ──────────────────────────────────────────
    {
        "category": "crypto_specific",
        "market": "crypto",
        "title": "Bitcoin Halving 4-Year Cycle",
        "content": "BTC halving reduces block reward by 50% every 210,000 blocks (~4 years). Historical pattern: 12-18 months after halving = bull market peak. 2012 halving: +5000% over 12 months. 2016 halving: +2000% over 18 months. 2020 halving: +700% over 18 months. 2024 halving: cycle in progress. Demand shock (ETFs) may amplify. Pattern becomes less pronounced as market matures.",
        "importance": 9,
        "tags": ["crypto_specific", "crypto", "crypto_bullish", "macro_cycle"],
    },
    {
        "category": "crypto_specific",
        "market": "crypto",
        "title": "Alt-Season Indicator",
        "content": "Alt-season occurs when BTC dominance (BTC market cap / total crypto market cap) falls below 50%. Sequence: BTC rallies first — ETH follows (2-4 weeks after BTC) — large-cap alts (LTC, SOL, AVAX) — small-cap alts. Timing: alt-season typically 6-9 months after BTC halving. Signal: when BTC dominance is falling AND BTC is above its 200-day MA.",
        "importance": 8,
        "tags": ["crypto_specific", "crypto", "crypto_bullish", "greed"],
    },
    {
        "category": "crypto_specific",
        "market": "crypto",
        "title": "Funding Rate Extremes — Contrarian Signal",
        "content": "Perpetual futures funding rate measures leverage direction. Rate > 0.1% per 8h = crowded long = likely reversal. Rate < -0.05% per 8h = crowded short = potential squeeze up. Historical: funding > 0.15% = bearish signal, BTC falls 15-30% within 2 weeks in 80% of cases. Best BTC buying signals: funding rate deeply negative + price at support + extreme fear F&G.",
        "importance": 9,
        "tags": ["crypto_specific", "crypto", "funding_extreme", "funding_negative", "crowded_long", "crowded_short"],
    },
    {
        "category": "crypto_specific",
        "market": "crypto",
        "title": "BTC ETF Approval — Demand Shock",
        "content": "US Bitcoin Spot ETF approved Jan 2024. First week: $10B+ inflows. BlackRock IBIT became fastest ETF to $10B in history. ETF demand is structurally different from exchange demand — pension funds and wealth managers can now hold BTC. ETF launch days and major institutional announcements can move BTC 5-15% quickly.",
        "importance": 9,
        "tags": ["crypto_specific", "crypto", "crypto_bullish", "crypto_regulatory"],
    },
    {
        "category": "crypto_specific",
        "market": "crypto",
        "title": "Stablecoin Market Cap — Liquidity Gauge",
        "content": "Total stablecoin market cap (USDT + USDC + DAI etc.) measures dry powder waiting to enter crypto. Rising stablecoin market cap + rising BTC = bullish (new money entering). Falling stablecoin market cap = money leaving the ecosystem = bearish. After a crash, stablecoin market cap often stays elevated for months — this dry powder is the fuel for the next rally.",
        "importance": 7,
        "tags": ["crypto_specific", "crypto", "crypto_bullish"],
    },
    {
        "category": "crypto_specific",
        "market": "crypto",
        "title": "On-Chain Whale Movements — Signal",
        "content": "Large BTC wallet moves: when long-dormant wallets (5+ years inactive) move coins = bear signal (old holders selling). When exchange BTC reserves fall = bull signal (coins moving to cold storage, less selling pressure). When Coinbase premium (US price vs offshore) goes positive = institutional buying. Whale wallet monitoring on Glassnode provides 24-48h leading indicator.",
        "importance": 7,
        "tags": ["crypto_specific", "crypto"],
    },
    {
        "category": "crypto_specific",
        "market": "crypto",
        "title": "Bitcoin Dominance Cycle",
        "content": "BTC dominance peaks at cycle top (70-75%), then falls as alts capture more value. At bottom of bear market: dominance rises to 60-65% as alts are sold to buy BTC (quality rotation). In early bull: BTC dominance rises as BTC leads. In mid bull: dominance falls as ETH and alts catch up. Falling dominance from 65%+ = alt-season starting.",
        "importance": 7,
        "tags": ["crypto_specific", "crypto", "crypto_bullish", "crypto_bearish"],
    },
    {
        "category": "crypto_specific",
        "market": "crypto",
        "title": "DeFi Risk — Smart Contract + Liquidity",
        "content": "DeFi protocols carry smart contract risk (code exploits) and liquidity risk (bank runs). History: $10B+ lost in DeFi hacks since 2020. Major hacks cause BTC/ETH to fall 5-15% due to contagion fear. Largest: Ronin Network ($625M, March 2022). Signal: if top-5 DeFi protocol is hacked, expect immediate 10-20% broad crypto selloff.",
        "importance": 8,
        "tags": ["crypto_specific", "crypto", "contagion_risk", "risk_off", "crypto_bearish"],
    },
    {
        "category": "crypto_specific",
        "market": "crypto",
        "title": "Crypto Correlation with Nasdaq",
        "content": "BTC-Nasdaq 30-day rolling correlation: bull market tops (2021): 0.25-0.40. Bear market (2022): 0.80-0.90. Correlation rises in risk-off and falls in crypto-specific bull. When correlation is high: treat BTC as tech stock. When correlation breaks down (BTC rises while Nasdaq flat): crypto-specific catalyst active (halving, ETF, institutional adoption).",
        "importance": 8,
        "tags": ["crypto_specific", "crypto", "us_stocks", "risk_off"],
    },
    {
        "category": "crypto_specific",
        "market": "crypto",
        "title": "Crypto Perpetual vs Spot Premium",
        "content": "When perpetual futures trade at 0.5%+ premium to spot: aggressive long leverage = contrarian sell signal. When perpetual trades at 0.5% discount to spot: bearish sentiment = potential contrarian buy. Combined with funding rate: if both premium and funding positive = leveraged longs overextended. High volume + discount = capitulation buying (strong buy signal).",
        "importance": 8,
        "tags": ["crypto_specific", "crypto", "funding_high", "crowded_long"],
    },
    {
        "category": "crypto_specific",
        "market": "crypto",
        "title": "Bitcoin Miner Capitulation Signal",
        "content": "When BTC price falls below miner break-even cost ($25-35k for most miners in 2024), miners sell BTC reserves to pay costs. This is a miner capitulation event — historically, major bottoms form within 4-8 weeks. Signal: hash ribbon indicator turns bearish (30-day MA of hashrate crosses below 60-day MA). After miner capitulation ends, BTC rallied 40%+ in 2015, 2018, 2022.",
        "importance": 7,
        "tags": ["crypto_specific", "crypto", "extreme_fear", "oversold"],
    },
    {
        "category": "crypto_specific",
        "market": "crypto",
        "title": "Fear and Greed Index — Crypto Specific",
        "content": "Crypto F&G < 20 (Extreme Fear): historically 80% probability of positive 90-day return. F&G 20-40 (Fear): cautiously bullish. F&G 60-80 (Greed): reduce sizing, take partial profits. F&G > 80 (Extreme Greed): sell 25-50% position, tighten stops. Best buys: F&G < 25 + BTC below 200-day MA. Best sells: F&G > 80 + BTC 40%+ above 200-day MA.",
        "importance": 8,
        "tags": ["crypto_specific", "crypto", "extreme_fear", "extreme_greed"],
    },
    {
        "category": "crypto_specific",
        "market": "crypto",
        "title": "Tether USDT Reserve Concerns",
        "content": "USDT (Tether) is largest stablecoin ($100B+). Concerns: reserve composition unclear, past attestation issues. If USDT loses peg or is shut down: BTC could fall 50-70% as crypto's main trading currency collapses. USDC is more transparent (Circle audited). Monitoring: USDT depeg of more than 0.5% from $1 = emergency signal. Historical near-miss: May 2022 briefly to $0.96.",
        "importance": 8,
        "tags": ["crypto_specific", "crypto", "contagion_risk", "risk_off"],
    },
    {
        "category": "crypto_specific",
        "market": "crypto",
        "title": "Exchange Flows — Buy vs Sell Signal",
        "content": "Bitcoin exchange net flows: coins moving TO exchanges = selling pressure (bearish). Coins moving FROM exchanges = accumulation, less sell pressure (bullish). Bull market: sustained exchange outflows over weeks = price going up with reduced supply. Bear market: exchange inflows spike = panic selling. Best time to buy: after a spike in exchange inflows (panic sellers exhausted).",
        "importance": 7,
        "tags": ["crypto_specific", "crypto", "extreme_fear", "oversold"],
    },
    {
        "category": "crypto_specific",
        "market": "crypto",
        "title": "Realized Price — Key Support Level",
        "content": "BTC realized price = average price all BTC was last moved (on-chain cost basis). When BTC spot price falls below realized price: most holders are underwater = capitulation zone = historically strong buy. 2022: realized price was ~$21k, BTC bottomed at $15.5k. 2018: realized price ~$6k, BTC bottomed at $3.2k. Being 20%+ below realized price = major buying opportunity.",
        "importance": 8,
        "tags": ["crypto_specific", "crypto", "extreme_fear", "oversold"],
    },
    {
        "category": "crypto_specific",
        "market": "crypto",
        "title": "SOL vs ETH — Alt Risk Profile",
        "content": "ETH alternatives (SOL, AVAX, Polygon) rally most in early-mid bull markets. In bear markets: these fall 85-95% while BTC falls 70-80%. SOL went from $260 (Nov 2021) to $8 (Dec 2022) = -97%. Always hold a higher % of BTC/ETH vs alts in bear markets. In bull: rotate from BTC to ETH (safer alt exposure), then to large-cap alts last.",
        "importance": 7,
        "tags": ["crypto_specific", "crypto", "crypto_bullish", "crypto_bearish"],
    },
    {
        "category": "crypto_specific",
        "market": "crypto",
        "title": "Liquidation Cascade — How They Work",
        "content": "When BTC drops to a level where many long positions are liquidated (visible in open interest data), those liquidations add sell pressure, triggering more liquidations: a cascade. Typical cascade size: $500M-$2B liquidated, price falls additional 3-8% beyond what triggered it. After cascade: price bounces 2-4% immediately as short sellers cover.",
        "importance": 8,
        "tags": ["crypto_specific", "crypto", "crowded_long", "vix_high"],
    },
    {
        "category": "crypto_specific",
        "market": "crypto",
        "title": "Ethereum Gas Fee as Activity Signal",
        "content": "High ETH gas fees (> 50 gwei): DeFi and NFT activity is high = bull market signal. Very low gas (< 5 gwei): network activity dropping = potential bear. ETH staking APR: 4-6% normal, rising above 8% signals high demand for block space. ETH deflationary mechanism (EIP-1559) burns more ETH at high usage: net deflationary when gas > ~15 gwei.",
        "importance": 6,
        "tags": ["crypto_specific", "crypto", "crypto_bullish"],
    },
    {
        "category": "crypto_specific",
        "market": "crypto",
        "title": "BTC vs ETH Ratio Trading",
        "content": "ETH/BTC ratio: 0.04-0.08 is historical normal range. Above 0.08: ETH overvalued vs BTC, expect ratio to revert. Below 0.04: ETH undervalued, buy ETH. Best time to buy ETH outright: when ETH/BTC ratio at multi-year lows AND BTC in early bull market. ETH typically outperforms BTC by 50-200% in the second half of a bull cycle.",
        "importance": 6,
        "tags": ["crypto_specific", "crypto", "crypto_bullish"],
    },
    {
        "category": "crypto_specific",
        "market": "crypto",
        "title": "Retail vs Institutional Accumulation",
        "content": "On-chain data: small wallet accumulation (< 1 BTC) continues even in bear markets — retail DCA. Large wallet accumulation (100-1000 BTC, OTC desks) precedes bull runs by 2-4 months. When both small and large wallets accumulate simultaneously: strong bull signal. When retail buys but whales sell (distribution): topping pattern.",
        "importance": 6,
        "tags": ["crypto_specific", "crypto", "crypto_bullish"],
    },
    {
        "category": "crypto_specific",
        "market": "crypto",
        "title": "Grayscale Premium — Institutional Signal",
        "content": "GBTC (Grayscale Bitcoin Trust) premium/discount to NAV: positive premium = institutional demand exceeds supply = bullish. Negative discount = institutions selling. GBTC discount peaked at -49% in Dec 2022 (sell pressure). After ETF conversion Jan 2024: GBTC became just another ETF. Monitor total ETF flows (IBIT, FBTC, GBTC combined) as institutional demand signal.",
        "importance": 6,
        "tags": ["crypto_specific", "crypto", "crypto_bullish"],
    },
    {
        "category": "crypto_specific",
        "market": "crypto",
        "title": "Crypto Market Hours — Asia Premium",
        "content": "Crypto is 24/7 but has time-based patterns: 8-10AM UTC (London open) often triggers momentum. 1-4PM UTC (NY open) highest volume and volatility. 10PM-2AM UTC (Asia retail hours) can cause random moves with low liquidity. Best signal quality: 1PM-9PM UTC. Weekend moves are often reversed Monday 1-3PM UTC when institutional trading resumes.",
        "importance": 6,
        "tags": ["crypto_specific", "crypto"],
    },
    {
        "category": "crypto_specific",
        "market": "crypto",
        "title": "NFT Market as Sentiment Indicator",
        "content": "NFT market is the most speculative layer of crypto. NFT floor prices peak 4-8 weeks BEFORE BTC top. When NFT volumes collapse while BTC is still near highs: sell signal. When NFTs start recovering while BTC still near bottom: speculative recovery starting. Bored Apes peak (April 2022: floor $420k) preceded BTC peak by 1 month.",
        "importance": 5,
        "tags": ["crypto_specific", "crypto", "extreme_greed", "greed"],
    },
    {
        "category": "crypto_specific",
        "market": "crypto",
        "title": "Crypto Weekend Risk Reduction",
        "content": "Crypto markets operate 24/7 but liquidity is 40-60% lower on weekends. Weekend BTC moves of 5-10% are common with thin order books. Large liquidations cascade faster with lower liquidity. Reduce position sizes Friday evening, set wider stops or take partial profits before weekend if holding leveraged positions.",
        "importance": 6,
        "tags": ["crypto_specific", "crypto", "risk_management"],
    },
    {
        "category": "crypto_specific",
        "market": "crypto",
        "title": "Bitcoin Power Law — Long-Term Fair Value",
        "content": "Bitcoin follows a power law relationship with time. Long-term fair value model: price = function of days since genesis block. Model suggests $100k by 2025, $1M by 2035 at current trajectory. Useful for: if BTC is 60%+ below the power law corridor (as in 2022), it is historically cheap. If 100%+ above, historically expensive. Not useful for short-term trading.",
        "importance": 5,
        "tags": ["crypto_specific", "crypto"],
    },

    # ── Economic Indicators (12 entries) ──────────────────────────────────────
    {
        "category": "economic_indicators",
        "market": "all",
        "title": "ISM PMI — Business Cycle Gauge",
        "content": "ISM Manufacturing PMI above 50 = expansion, below 50 = contraction. Services PMI above 50 = economy healthy. Manufacturing PMI below 48 for 3+ months = recession probability > 60%. New orders subindex is the most forward-looking component. When New Orders rise while overall PMI is below 50: recovery beginning.",
        "importance": 8,
        "tags": ["economic_indicators", "recession_risk", "macro_cycle"],
    },
    {
        "category": "economic_indicators",
        "market": "all",
        "title": "Retail Sales — Consumer Health",
        "content": "US retail sales (released monthly): controls for inflation. Core retail sales (ex-auto, ex-gas) is cleanest consumer signal. Below 0% monthly = consumer pulling back = potential recession signal. Above 0.5% monthly = consumer strong = hawkish Fed signal. Weak retail sales + high consumer debt = recession warning.",
        "importance": 7,
        "tags": ["economic_indicators", "recession_risk", "nfp_event"],
    },
    {
        "category": "economic_indicators",
        "market": "all",
        "title": "Jobless Claims — Weekly Leading Indicator",
        "content": "Initial jobless claims: below 250k = healthy labor market. 250-350k = softening. Above 350k = layoffs accelerating = recession approaching. 4-week moving average smooths volatility. Continuing claims rising + initial claims rising = unemployment rate going up = Fed has room to cut. First major spike in claims often leads recession start by 3-6 months.",
        "importance": 8,
        "tags": ["economic_indicators", "recession_risk", "rate_cut_cycle"],
    },
    {
        "category": "economic_indicators",
        "market": "all",
        "title": "Housing Market — Economic Leading Indicator",
        "content": "Housing starts and building permits lead the economy by 6-12 months. Home prices (Case-Shiller): falling 5%+ YoY = consumer wealth effect reducing spending. Mortgage rates (30Y fixed): above 7% = housing market freezes, construction falls. Housing is most rate-sensitive sector: 300bps in rates reduces housing activity 30-40%.",
        "importance": 7,
        "tags": ["economic_indicators", "rate_hike_cycle", "recession_risk"],
    },
    {
        "category": "economic_indicators",
        "market": "all",
        "title": "Consumer Confidence — Sentiment Gauge",
        "content": "University of Michigan consumer sentiment and Conference Board consumer confidence: leading indicators for retail spending and labor market. When confidence falls below 60 (UMich scale): recession risk high. Current jobs abundance subindex most predictive of unemployment rate changes. Confidence diverging from actual spending: they will converge within 2-3 months.",
        "importance": 6,
        "tags": ["economic_indicators", "recession_risk"],
    },
    {
        "category": "economic_indicators",
        "market": "all",
        "title": "GDP Revision Pattern",
        "content": "US GDP: first estimate — 30-day revision — 60-day revision. First estimate often revised significantly. Two consecutive quarters of negative GDP = technical recession. However, NBER (official recession judge) uses broader metrics and often calls recession months later. Markets trade the narrative, not official definition.",
        "importance": 6,
        "tags": ["economic_indicators", "recession_risk", "gdp_event"],
    },
    {
        "category": "economic_indicators",
        "market": "all",
        "title": "Treasury Yield Curve as Economic Map",
        "content": "Yield curve shape: steepening (long rates rising faster than short) = economic growth, inflation expectations rising = bullish risk assets. Flattening = growth slowing. Inverted (short > long) = recession signal. Bull steepener (long flat, short falls) = Fed cutting = best case for risk assets. Bear steepener (long rises, short flat) = inflation concern = worst case.",
        "importance": 9,
        "tags": ["economic_indicators", "recession_risk", "rate_hike_cycle", "rate_cut_cycle", "yield_curve_inverted"],
    },
    {
        "category": "economic_indicators",
        "market": "all",
        "title": "PCE vs CPI Divergence Signals",
        "content": "When PCE and CPI diverge: check healthcare and housing components. Shelter in CPI lags actual rents by 12-18 months due to lease renewal timing. This means CPI shelter can stay elevated even after real rents fall. When super-core CPI (services ex-housing ex-energy) falls: actual inflation cooling, Fed can pivot sooner.",
        "importance": 7,
        "tags": ["economic_indicators", "rate_cut_cycle", "cpi_event"],
    },
    {
        "category": "economic_indicators",
        "market": "india_stocks",
        "title": "India IIP and PMI — Economic Health",
        "content": "India Index of Industrial Production (IIP): above 5% growth = expansion. Below 2% = slowdown. India Manufacturing PMI: above 55 = strong. 50-55 = normal growth. Below 50 = contraction. India GDP growth 6-7% is normal, below 5% causes market concern, above 8% is euphoric. Quarterly GDP advance estimate released in February is key.",
        "importance": 6,
        "tags": ["economic_indicators", "india_stocks", "macro_cycle"],
    },
    {
        "category": "economic_indicators",
        "market": "india_stocks",
        "title": "India Monsoon — Agricultural Macro Impact",
        "content": "Monsoon (June-September) affects 50% of India's agricultural economy and rural consumption. Below normal monsoon (< 95% of long-period average): FMCG rural demand falls, 2-wheel auto sales fall, fertilizer stocks impacted. Good monsoon: FMCG, agri-inputs, rural finance companies rally. Monsoon forecast (IMD April) moves Nifty 0.5-1%.",
        "importance": 6,
        "tags": ["economic_indicators", "india_stocks"],
    },
    {
        "category": "economic_indicators",
        "market": "all",
        "title": "Baltic Dry Index — Global Trade Signal",
        "content": "Baltic Dry Index (BDI): measures cost of shipping dry bulk commodities (iron ore, grain, coal). Rising BDI = global trade expanding = bullish for global growth, mining stocks. Falling BDI = overcapacity or demand collapse = global slowdown signal. BDI bottomed at 290 in 2016 (lowest since 1985) — global trade/materials rally followed.",
        "importance": 5,
        "tags": ["economic_indicators", "macro_cycle"],
    },
    {
        "category": "economic_indicators",
        "market": "all",
        "title": "M2 Money Supply Growth",
        "content": "M2 money supply annual growth: above 10% = expansionary, supports asset prices. 0-5% = neutral. Negative M2 growth (first time since 1930s in 2023): liquidity drain, bearish for risk assets. QE directly causes M2 expansion. Fiscal stimulus (checks, unemployment) also expands M2. Crypto rallied when M2 grew 30% in 2020-2021. Fell when M2 turned negative in 2022-2023.",
        "importance": 7,
        "tags": ["economic_indicators", "macro_cycle", "crypto_bullish", "risk_on"],
    },

    # ── India Specific (12 entries) ────────────────────────────────────────────
    {
        "category": "india_specific",
        "market": "india_stocks",
        "title": "India Budget Day Playbook",
        "content": "Union Budget (first week of February): markets react sharply to fiscal stimulus, tax changes, capex targets. Historic pattern: Nifty falls 1-2% in 2 weeks before budget (uncertainty), then rallies post-budget if no bad surprises. Best budget plays: infrastructure stocks (L&T, NCC) if capex announced; PSU banks if recapitalization; FMCG if consumption boost.",
        "importance": 8,
        "tags": ["india_specific", "india_stocks", "high_impact_event"],
    },
    {
        "category": "india_specific",
        "market": "india_stocks",
        "title": "FII vs DII Flows — Market Direction",
        "content": "FII (Foreign Institutional Investors) are the marginal price setters for Nifty. FII net selling of Rs 10,000+ crore/month = Nifty headwind. FII buying = tailwind. DII (domestic mutual funds, LIC) are the counter-balancing force — they buy when FIIs sell. Since 2020, DII SIP inflows Rs 15,000+ crore/month provide floor. Sustained FII selling despite DII buying = market under pressure.",
        "importance": 9,
        "tags": ["india_specific", "india_stocks", "risk_off"],
    },
    {
        "category": "india_specific",
        "market": "india_stocks",
        "title": "Nifty F&O Expiry Volatility",
        "content": "Weekly Nifty options expire every Thursday. Max pain (price where maximum options expire worthless) tends to be a gravity point on expiry day. Last hour before expiry: extreme volatility as market makers hedge gamma. Monthly expiry (last Thursday): larger moves. Strategy: avoid large directional positions on Thursday unless conviction is very high.",
        "importance": 8,
        "tags": ["india_specific", "india_stocks", "high_impact_event"],
    },
    {
        "category": "india_specific",
        "market": "india_stocks",
        "title": "Nifty vs Global Correlation",
        "content": "Nifty50 correlation with S&P500: 0.6-0.7 normally. Rises to 0.85-0.9 during global risk-off. India is a decoupled story but only mildly — when US sneezes, India catches a cold. Exception: India has domestic drivers (budget, elections, monsoon, RBI) that can cause Nifty to diverge. If India fundamentals are strong AND global risk-off is temporary, Nifty outperforms on the rebound.",
        "importance": 7,
        "tags": ["india_specific", "india_stocks", "risk_off"],
    },
    {
        "category": "india_specific",
        "market": "india_stocks",
        "title": "INR Weakness — Impact on India Markets",
        "content": "INR weakening: oil import costs rise (India imports 85% of oil) — current account deficit widens — FII outflows accelerate — Nifty falls. INR/USD above 87: inflationary pressure, RBI may hike or sell reserves to defend. IT sector benefits from INR weakness (USD revenues). Pharma exports also benefit. AVOID: OMCs (oil marketing companies like HPCL, BPCL) when INR weakening fast.",
        "importance": 8,
        "tags": ["india_specific", "india_stocks", "forex", "oil_high"],
    },
    {
        "category": "india_specific",
        "market": "india_stocks",
        "title": "India Election Year — Market Pattern",
        "content": "India general elections (every 5 years, May): historically, Nifty rises 15-30% in year before election as government boosts spending. Post-election uncertainty: Nifty volatile for 2-4 weeks after results. Incumbent winning = continuity = Nifty +3-5% next day. Surprise/hung parliament = Nifty -5-10%. 2019 election: Modi returned with majority — Nifty +7% next day.",
        "importance": 7,
        "tags": ["india_specific", "india_stocks", "geopolitical_risk"],
    },
    {
        "category": "india_specific",
        "market": "india_stocks",
        "title": "PSU Banks vs Private Banks India",
        "content": "Public sector banks (SBI, PNB, Canara): benefit from government capex cycles, recapitalization. Higher NPA risk, lower margins but cheap valuations. Private banks (HDFC, ICICI, Kotak): better asset quality, higher ROE, preferred by FIIs. In risk-off: PSU banks fall more. In recovery: PSU banks rally more from lower base. Nifty Bank index: 60% private, 40% PSU.",
        "importance": 6,
        "tags": ["india_specific", "india_stocks", "rate_hike_cycle"],
    },
    {
        "category": "india_specific",
        "market": "india_stocks",
        "title": "Reliance Industries — Nifty Bellwether",
        "content": "Reliance Industries has ~12% weight in Nifty50. RIL results (quarterly) can move Nifty 0.5-1%. Segments: O2C (oil refining), Retail, Jio (telecom). Oil price rise — O2C margins squeeze — RIL underperforms. Jio subscriber data monthly = telecom sector signal. RIL is FII favorite as India's largest company by market cap.",
        "importance": 7,
        "tags": ["india_specific", "india_stocks", "oil_high"],
    },
    {
        "category": "india_specific",
        "market": "india_stocks",
        "title": "India Small Cap vs Large Cap",
        "content": "India small caps (SMLCAP index) outperform large caps during: domestic growth cycles, mid-budget cycle, strong INR. Underperform during: global risk-off, rate hike cycles. Mid caps and small caps have 2x the drawdown of Nifty50 in corrections. In recovery: small caps gain 50-100% vs Nifty +25-40% in first year.",
        "importance": 6,
        "tags": ["india_specific", "india_stocks", "risk_off", "risk_on"],
    },
    {
        "category": "india_specific",
        "market": "india_stocks",
        "title": "Nifty Pharma — Defensive + Export Growth",
        "content": "Nifty Pharma = defensive domestic demand (generics) + US generic export opportunity. US FDA approval = stock +20-40% in a day. Warning letter/import alert = -20-30%. Sun Pharma, Dr. Reddy's, Cipla have large US exposure. During INR weakness: pharma exports become more profitable. Defensive relative to Nifty50 (beta ~0.6).",
        "importance": 6,
        "tags": ["india_specific", "india_stocks", "risk_off"],
    },
    {
        "category": "india_specific",
        "market": "india_stocks",
        "title": "India VIX — Fear Gauge",
        "content": "India VIX (implied volatility of Nifty options): above 20 = elevated fear, reduce leverage. Above 30 = high fear, only scalps. Above 40 = crisis level (only seen during COVID 2020, elections). India VIX typically inversely correlated with Nifty (-0.85). When India VIX spikes above 20 and Nifty is at support: contrarian buying opportunity. VIX above 25 before expiry = watch for Thursday spike.",
        "importance": 7,
        "tags": ["india_specific", "india_stocks", "vix_high", "risk_off"],
    },
    {
        "category": "india_specific",
        "market": "india_stocks",
        "title": "India Infrastructure Cycle",
        "content": "Government capex in India: roads (NHAI), railways (IRB, PNC), defense (HAL, BEL, Bharat Dynamics). Budget capex targets announced in February. Capex frontloading in Q1 (April-June). Infrastructure stocks lead 6-9 months before actual capex spend. L&T, KNR Constructions, NCC are pure plays. When government capex > 3% of GDP: infrastructure supercycle.",
        "importance": 6,
        "tags": ["india_specific", "india_stocks", "macro_cycle"],
    },
]


async def seed_knowledge_base(db: AsyncSession) -> None:
    count_result = await db.execute(select(func.count()).select_from(KnowledgeEntry).where(KnowledgeEntry.source == "system"))
    count = count_result.scalar()
    if count and count >= len(SEED_KNOWLEDGE):
        return   # already seeded

    for entry in SEED_KNOWLEDGE:
        existing = await db.execute(
            select(KnowledgeEntry).where(KnowledgeEntry.title == entry["title"])
        )
        if not existing.scalar_one_or_none():
            db.add(KnowledgeEntry(
                id=str(uuid.uuid4()),
                source="system",
                **entry,
            ))
    await db.commit()
